/**
 * Author:qiang
 * Date:2024/7/26
 * IDEA:SseHarmonyOS
 * FileName:NewStockBondFields
 */
export const StockField: Record<string,string> = {
    "APPLYCODE": "申购代码",
    "SECUABBR": "股票简称",
    "TRADINGCODE": "交易代码",
    "ISSUEPRICE": "实际发行价格",
    "ISSUEPRICEPLAN": "预估发行价格",
    "PEAISSUE": "发行市盈率",
    "SUCCRESULTNOTICEDATE": "中签公告日",
    "CAPPLYSHARE": "申购上限",
    "ALLOTRATEON": "中签率",
    "LISTINGDATE": "上市日期",
    "BOOKSTARTDATEON": "申购日期",
    "ISSUESHARE": "实际发行总量",
    "ISSUESHAREON": "实际网上发行数量",
    "CAPPLYPRICE": "实际网上申购所需资金",
    "CISSUESHAREPLAN": "计划发行总量",
    "ISSUESHAREONPLAN": "计划网上发行量",
    "BOARDNAME": "所属板块",
    "COMPROFILE": "公司简介",
    "BUSINESSSCOPE": "经营范围",
    "ISSUEALLOTNOON": "中签号",
    "REFUNDDATEON": "网上申购资金解冻日期",
    "LEADUNDERWRITER": "主承销商",
    "CAPPLYPRICEPLAN": "预估网上申购所需资金",
    "CAPPLYSHAREPLAN": "顶格申购所需资金",
    "NEWTOTRAISEAMT": "募集资金总额",
    "NEWNETRAISEAMT": "募集资金净额",
    "KEYCODE": "是否科创板",
    "TYPE": "类型",
    "ISPROFIT": "上市时尚未盈利",
    "ISDIFFVOTE": "是否存在投票权差异",
    "ISVIEFRAME": "是否具有协议控制架构",
    "ISSSYSTEM": "发行制度",
    "SETYPE": "是否是CDR类型",
    "STOCKCBX": "基础股票(X)与CDR(Y)的转换比例_X",
    "CDRCBY": "基础股票(X)与CDR(Y)的转换比例_Y",
  };
 export const BondField: Record<string,string> = {
    "APPLYCODE": "申购代码",
    "TRADINGCODE": "债券代码",
    "SECUABBR": "债券名称",
    "STOCKTRADINGCODE": "正股代码",
    "STOCKSECUABBR": "正股名称",
    "ISSUEPRICE": "发行价格",
    "CONVERTPRICE": "初始转股价格",
    "PREFERREDPLACINGCODE": "配售代码",
    "PREFERREDPLACINGNAME": "配售简称",
    "ISSUERRATING": "信用评级",
    "ISSUEVAL": "债券发行总额",
    "INTERESTTERM": "利率",
    "CAPPLYVOL": "申购上限",
    "BOOKSTARTDATEON": "申购日期",
    "SUCCRESULTNOTICEDATE": "中签公告日",
    "LISTINGDATE": "上市日期",
    "ALLOTRATEON": "中签率",
    "MATURITYYEAR": "债券年限（年）",
    "BONDTYPE": "债券类型",
    "ONLINEGSINVLWINNUM": "中签号",
    "OFFCAPPLYVOL": "网下认购数量上限",
    "TYPE": "类型"
  };
 export const StockBondFields :Record<string,string> = {
   "sglist": "今日申购"
 }